import { Link } from "gatsby"
import React from "react"
import { Container } from "react-bootstrap"
import SideBarsLayout from "../../components/shared/Layout/SideBarsLayout"
import BaseLayout from "../../components/static/BaseLayout"
import MainHeading from "../../components/static/MainHeading"

const CMSDesc = () => {
  return (
    <BaseLayout>
      <MainHeading 
        subHeading="Access to the content management system used for the ReInHerit digital hub"
        subText="Here you'll find the login and useful material on how to use the digital hub's content management system."
      >CMS Access</MainHeading>
      <Container fluid className="bg-white shadow p-sm-3 p-md-4 rounded">
      <SideBarsLayout
        left={
          <>
            <h2 className="h5">Important links</h2>
            <ul>
              <li>
                <a href="/admin/admin.html" target="_blank">
                  CMS Login
                </a>
              </li>
              <li>
                <Link to="/doc/authorization">Access documentation</Link>
              </li>
            </ul>
          </>
        }
      >
        <h2 className="h5">Basics</h2>
        <p>
          The content of the digital hub is dynamically generated by the content management system NetlifyCMS. During the second phase 
          of the digital-hub development (as part of the ReInHerit project) specific project members (moderators) will regularly add content to the hub's via the CMS.
          Currently it is not planned to open up the CMS access to a broader public. Nevertheless, if you want to make contributions regarding the content of the Hub, 
          please get in contact with one of our moderators.

        </p>
        <h2 className="h5">Prerequisites</h2>
        <ol>
          <li>Valid <a href="https://github.com/">github</a> account.</li>
          <li>Moderation status - please contact the digital hub development team if you need moderation access (and provide your github username).</li>
        </ol>
        <h2 className="h5">How to use</h2>
        <p>Check out the <a href="#">detailed manual</a> on how to use the digital hub's CMS.</p>
        <p>If you have any questions please first consider to check for already available solutions in the <a href="/doc/faq">FAQ section</a></p>
      </SideBarsLayout>
      </Container>
    </BaseLayout>
  )
}

export default CMSDesc
